<Project Sdk="Microsoft.NET.Sdk">
    
    <Import Project="..\tModLoader.targets" />

    <PropertyGroup>
        <AssemblyName>FargowiltasSouls</AssemblyName>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="lib\**\*" />
    </ItemGroup>

</Project>